"""Passwordless polkit grants for oysterAV service-lifecycle actions."""

from __future__ import annotations

import os
import re
import textwrap
from datetime import UTC, datetime
from pathlib import Path

from oyst_core.privileged.auth_grant_expire import install_expire_timer, remove_expire_timer
from oyst_core.privileged.auth_grant_scope import (
    EXPIRE_TIMER_UNIT,
    GRANT_STAMP_VERSION,
    SERVICE_LIFECYCLE_ACTION_IDS,
    format_expires,
    grant_expires_at,
    parse_expires,
)
from oyst_core.privileged.runner import run_command
from oyst_core.privileged.safe_write import write_text_nofollow
from oyst_core.schedule_linger import current_username

RULES_PATH = Path("/etc/polkit-1/rules.d/49-oysterav-service-lifecycle.rules")
# World-readable stamp: rules.d is typically root:polkitd mode 750, so unprivileged
# auth.status cannot read the rules file directly.
GRANT_STAMP_PATH = Path("/usr/local/share/oysterav/service-lifecycle.grant")
_USERNAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")


def _validate_username(user: str) -> str:
    cleaned = user.strip()
    if not _USERNAME_RE.fullmatch(cleaned):
        raise ValueError(f"invalid username: {user}")
    return cleaned


def build_service_lifecycle_rules(user: str) -> str:
    """JavaScript polkit rules granting YES for narrowed lifecycle actions."""
    username = _validate_username(user)
    action_checks = " ||\n            ".join(
        f'action.id == "{aid}"' for aid in SERVICE_LIFECYCLE_ACTION_IDS
    )
    return textwrap.dedent(
        f"""\
        /* oysterAV: passwordless service lifecycle for user {username}
         * Generated by: oyst-cli auth grant-service-lifecycle
         * Revoke with: oyst-cli auth revoke-service-lifecycle
         * Scope: systemctl-up (AV start/enable) + maldet-config only
         */
        polkit.addRule(function(action, subject) {{
            if (subject.user == "{username}" &&
                subject.active == true &&
                subject.local == true && (
            {action_checks}
            )) {{
                return polkit.Result.YES;
            }}
        }});
        """,
    )


def _write_grant_stamp(user: str, stamp_path: Path, *, expires: datetime) -> None:
    stamp_path.parent.mkdir(parents=True, exist_ok=True)
    body = f"user={user}\nexpires={format_expires(expires)}\nversion={GRANT_STAMP_VERSION}\n"
    write_text_nofollow(stamp_path, body, mode=0o644)


def _read_grant_stamp(stamp_path: Path) -> dict[str, str]:
    try:
        text = stamp_path.read_text(encoding="utf-8")
    except OSError:
        return {}
    out: dict[str, str] = {}
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        out[key.strip()] = value.strip()
    return out


def _parse_granted_user_from_rules(text: str) -> str | None:
    match = re.search(r'subject\.user\s*==\s*"([^"]+)"', text)
    return match.group(1) if match else None


def auth_status(
    *,
    rules_path: Path | None = None,
    stamp_path: Path | None = None,
    now: datetime | None = None,
) -> dict[str, object]:
    path = rules_path or RULES_PATH
    stamp = stamp_path or GRANT_STAMP_PATH
    granted_user: str | None = None
    present = False
    expires_raw: str | None = None
    expired = False
    stamp_fields = _read_grant_stamp(stamp)
    if stamp_fields.get("user"):
        present = True
        granted_user = stamp_fields["user"]
        expires_raw = stamp_fields.get("expires")
        exp = parse_expires(expires_raw) if expires_raw else None
        if exp is not None:
            clock = now or datetime.now(UTC)
            if clock.tzinfo is None:
                clock = clock.replace(tzinfo=UTC)
            expired = clock >= exp
        elif stamp_fields:
            # Legacy stamp without expires — treat as needing refresh.
            expired = True

    rules_readable = False
    try:
        rules_readable = path.is_file()
    except OSError as exc:
        if granted_user is None:
            return {
                "granted": False,
                "expired": False,
                "expires": None,
                "rules_path": str(path),
                "granted_user": None,
                "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
                "current_user": current_username(),
                "error": str(exc),
                "stamp_path": str(stamp),
            }

    if rules_readable:
        present = True
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            if granted_user is None:
                return {
                    "granted": False,
                    "expired": False,
                    "expires": None,
                    "rules_path": str(path),
                    "granted_user": None,
                    "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
                    "current_user": current_username(),
                    "error": str(exc),
                    "stamp_path": str(stamp),
                }
        else:
            parsed = _parse_granted_user_from_rules(text)
            if parsed:
                granted_user = parsed

    effective = bool(present and granted_user is not None and not expired)
    timer_unit = Path("/etc/systemd/system") / EXPIRE_TIMER_UNIT
    timer_installed = False
    try:
        timer_installed = timer_unit.is_file()
    except OSError:
        timer_installed = False
    return {
        "granted": effective,
        "expired": expired,
        "expires": expires_raw,
        "rules_path": str(path),
        "granted_user": granted_user,
        "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
        "current_user": current_username(),
        "stamp_path": str(stamp),
        "stamp_present": bool(stamp_fields),
        "expire_timer_installed": timer_installed,
        "expire_timer_unit": EXPIRE_TIMER_UNIT,
    }


def grant_service_lifecycle(
    user: str | None = None,
    *,
    prefix: Path | None = None,
) -> dict[str, object]:
    """Install polkit rules.d grant (requires root)."""
    if os.geteuid() != 0 and prefix is None:
        return {
            "ok": False,
            "message": "Must run as root (sudo oyst-cli auth grant-service-lifecycle)",
            "rules_path": str(RULES_PATH),
        }

    target_user = _validate_username(user or current_username())
    path = (
        prefix / "etc" / "polkit-1" / "rules.d" / "49-oysterav-service-lifecycle.rules"
        if prefix
        else RULES_PATH
    )
    stamp = (
        prefix / "usr" / "local" / "share" / "oysterav" / "service-lifecycle.grant"
        if prefix
        else GRANT_STAMP_PATH
    )
    expires = grant_expires_at()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_text_nofollow(path, build_service_lifecycle_rules(target_user), mode=0o644)
        _write_grant_stamp(target_user, stamp, expires=expires)
        install_expire_timer(prefix=prefix)
        if prefix is None:
            run_command(["systemctl", "reload", "polkit"], timeout=15)
    except (OSError, ValueError) as exc:
        try:
            if path.is_file():
                path.unlink()
            if stamp.is_file():
                stamp.unlink()
            remove_expire_timer(prefix=prefix)
        except OSError:
            pass
        return {
            "ok": False,
            "message": (
                f"Grant aborted (expire timer required): {exc}. "
                "Passwordless YES was not left active without a working expire timer."
            ),
            "rules_path": str(path),
            "granted_user": target_user,
        }

    return {
        "ok": True,
        "message": (
            f"Granted passwordless AV start/enable for user {target_user} "
            f"until {format_expires(expires)}. "
            "Applies to systemctl-up + maldet-config only; stop/disable still prompt."
        ),
        "rules_path": str(path),
        "stamp_path": str(stamp),
        "granted_user": target_user,
        "expires": format_expires(expires),
        "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
    }


def revoke_service_lifecycle(*, prefix: Path | None = None) -> dict[str, object]:
    """Remove polkit rules.d grant (requires root)."""
    if os.geteuid() != 0 and prefix is None:
        return {
            "ok": False,
            "message": "Must run as root (sudo oyst-cli auth revoke-service-lifecycle)",
            "rules_path": str(RULES_PATH),
        }

    path = (
        prefix / "etc" / "polkit-1" / "rules.d" / "49-oysterav-service-lifecycle.rules"
        if prefix
        else RULES_PATH
    )
    stamp = (
        prefix / "usr" / "local" / "share" / "oysterav" / "service-lifecycle.grant"
        if prefix
        else GRANT_STAMP_PATH
    )
    existed = path.is_file() or stamp.is_file()
    try:
        if path.is_file():
            path.unlink()
        if stamp.is_file():
            stamp.unlink()
        remove_expire_timer(prefix=prefix)
        if prefix is None and existed:
            run_command(["systemctl", "reload", "polkit"], timeout=15)
    except OSError as exc:
        return {"ok": False, "message": str(exc), "rules_path": str(path)}

    return {
        "ok": True,
        "message": "Revoked service-lifecycle passwordless grant"
        if existed
        else "No service-lifecycle grant was installed",
        "rules_path": str(path),
        "stamp_path": str(stamp),
        "removed": existed,
    }


def migrate_grant_on_helper_install(*, prefix: Path | None = None) -> dict[str, object] | None:
    """Rewrite legacy YES grants to systemctl-up scope when stamp exists."""
    stamp = (
        prefix / "usr" / "local" / "share" / "oysterav" / "service-lifecycle.grant"
        if prefix
        else GRANT_STAMP_PATH
    )
    fields = _read_grant_stamp(stamp)
    user = fields.get("user")
    if not user:
        return None
    return grant_service_lifecycle(user, prefix=prefix)
