"""Passwordless polkit grants for oysterAV service-lifecycle actions."""

from __future__ import annotations

import os
import re
import textwrap
from pathlib import Path

from oyst_core.privileged.install_privileged_helper import SERVICE_LIFECYCLE_ACTION_IDS
from oyst_core.privileged.runner import run_command
from oyst_core.privileged.safe_write import write_text_nofollow
from oyst_core.schedule_linger import current_username

RULES_PATH = Path("/etc/polkit-1/rules.d/49-oysterav-service-lifecycle.rules")
# World-readable stamp: rules.d is typically root:polkitd mode 750, so unprivileged
# auth.status cannot read the rules file directly.
GRANT_STAMP_PATH = Path("/usr/local/share/oysterav/service-lifecycle.grant")
_USERNAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")


def _validate_username(user: str) -> str:
    cleaned = user.strip()
    if not _USERNAME_RE.fullmatch(cleaned):
        raise ValueError(f"invalid username: {user}")
    return cleaned


def build_service_lifecycle_rules(user: str) -> str:
    """JavaScript polkit rules granting YES for service-lifecycle actions."""
    username = _validate_username(user)
    action_checks = " ||\n            ".join(
        f'action.id == "{aid}"' for aid in SERVICE_LIFECYCLE_ACTION_IDS
    )
    return textwrap.dedent(
        f"""\
        /* oysterAV: passwordless service lifecycle for user {username}
         * Generated by: oyst-cli auth grant-service-lifecycle
         * Revoke with: oyst-cli auth revoke-service-lifecycle
         */
        polkit.addRule(function(action, subject) {{
            if (subject.user == "{username}" && (
            {action_checks}
            )) {{
                return polkit.Result.YES;
            }}
        }});
        """,
    )


def _write_grant_stamp(user: str, stamp_path: Path) -> None:
    stamp_path.parent.mkdir(parents=True, exist_ok=True)
    write_text_nofollow(stamp_path, f"user={user}\n", mode=0o644)


def _read_grant_stamp(stamp_path: Path) -> str | None:
    try:
        text = stamp_path.read_text(encoding="utf-8")
    except OSError:
        return None
    match = re.search(r"^user=([a-z_][a-z0-9_-]{0,31})\s*$", text, re.MULTILINE)
    return match.group(1) if match else None


def _parse_granted_user_from_rules(text: str) -> str | None:
    match = re.search(r'subject\.user\s*==\s*"([^"]+)"', text)
    return match.group(1) if match else None


def auth_status(
    *,
    rules_path: Path | None = None,
    stamp_path: Path | None = None,
) -> dict[str, object]:
    path = rules_path or RULES_PATH
    stamp = stamp_path or GRANT_STAMP_PATH
    granted_user: str | None = None
    present = False

    stamp_user = _read_grant_stamp(stamp)
    if stamp_user:
        present = True
        granted_user = stamp_user

    if path.is_file():
        present = True
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            # Directory not readable (common: root:polkitd 750) — rely on stamp.
            if granted_user is None:
                return {
                    "granted": False,
                    "rules_path": str(path),
                    "granted_user": None,
                    "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
                    "current_user": current_username(),
                    "error": str(exc),
                    "stamp_path": str(stamp),
                }
        else:
            parsed = _parse_granted_user_from_rules(text)
            if parsed:
                granted_user = parsed

    return {
        "granted": present and granted_user is not None,
        "rules_path": str(path),
        "granted_user": granted_user,
        "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
        "current_user": current_username(),
        "stamp_path": str(stamp),
    }


def grant_service_lifecycle(
    user: str | None = None,
    *,
    prefix: Path | None = None,
) -> dict[str, object]:
    """Install polkit rules.d grant (requires root)."""
    if os.geteuid() != 0 and prefix is None:
        return {
            "ok": False,
            "message": "Must run as root (sudo oyst-cli auth grant-service-lifecycle)",
            "rules_path": str(RULES_PATH),
        }

    target_user = _validate_username(user or current_username())
    path = (
        prefix / "etc" / "polkit-1" / "rules.d" / "49-oysterav-service-lifecycle.rules"
        if prefix
        else RULES_PATH
    )
    stamp = (
        prefix / "usr" / "local" / "share" / "oysterav" / "service-lifecycle.grant"
        if prefix
        else GRANT_STAMP_PATH
    )
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_text_nofollow(path, build_service_lifecycle_rules(target_user), mode=0o644)
        _write_grant_stamp(target_user, stamp)
        if prefix is None:
            run_command(["systemctl", "reload", "polkit"], timeout=15)
    except (OSError, ValueError) as exc:
        return {
            "ok": False,
            "message": str(exc),
            "rules_path": str(path),
            "granted_user": target_user,
        }

    return {
        "ok": True,
        "message": (
            f"Granted passwordless service lifecycle for user {target_user}. "
            "Applies to systemctl/maldet-config helper actions only."
        ),
        "rules_path": str(path),
        "stamp_path": str(stamp),
        "granted_user": target_user,
        "actions": list(SERVICE_LIFECYCLE_ACTION_IDS),
    }


def revoke_service_lifecycle(*, prefix: Path | None = None) -> dict[str, object]:
    """Remove polkit rules.d grant (requires root)."""
    if os.geteuid() != 0 and prefix is None:
        return {
            "ok": False,
            "message": "Must run as root (sudo oyst-cli auth revoke-service-lifecycle)",
            "rules_path": str(RULES_PATH),
        }

    path = (
        prefix / "etc" / "polkit-1" / "rules.d" / "49-oysterav-service-lifecycle.rules"
        if prefix
        else RULES_PATH
    )
    stamp = (
        prefix / "usr" / "local" / "share" / "oysterav" / "service-lifecycle.grant"
        if prefix
        else GRANT_STAMP_PATH
    )
    existed = path.is_file() or stamp.is_file()
    try:
        if path.is_file():
            path.unlink()
        if stamp.is_file():
            stamp.unlink()
        if prefix is None and existed:
            run_command(["systemctl", "reload", "polkit"], timeout=15)
    except OSError as exc:
        return {"ok": False, "message": str(exc), "rules_path": str(path)}

    return {
        "ok": True,
        "message": "Revoked service-lifecycle passwordless grant"
        if existed
        else "No service-lifecycle grant was installed",
        "rules_path": str(path),
        "stamp_path": str(stamp),
        "removed": existed,
    }
